apiVersion: v1
kind: Service
metadata:
  name: hello-world-node-service
spec:
  selector:
    app: hello-world-node
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30000  # Change port number if needed
